title: Scotty Test Blog
description: Email → Markdown → Jekyll
theme: minima
url: "https://tchan1002.github.io"
baseurl: "/jekyll-test-blog"   # <= repo name, include leading slash
markdown: kramdown
